import 'package:bengali_food/models/meal.dart';
import 'package:flutter/material.dart';

import './models/Category.dart';

const Dummy1 = const [
  Category(id: 'c1', title: 'Fast Food', color: Colors.amber),
  Category(id: 'c2', title: 'Bhajas', color: Colors.cyan),
  Category(id: 'c3', title: 'Misti', color: Colors.orange),
  Category(id: 'c4', title: 'Specials', color: Colors.blue),
];
const Dummy2 = const [
  Category(id: 'c5', title: 'Fish', color: Colors.lightGreen),
  Category(id: 'c6', title: 'Mangsho', color: Colors.redAccent),
  Category(id: 'c7', title: 'Torkari', color: Colors.teal),
];

const Dummy_meals = const [
  Meal(
      title: 'Fuchka',
      imageUrl: 'assets/foods/1.jpg',
      id: 'FF1',
      category: 'c1',
      isMustTry: true,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Papri Chaat',
      imageUrl: 'assets/foods/2.jpg',
      id: 'FF2',
      category: 'c1',
      isMustTry: true,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Singara',
      imageUrl: 'assets/foods/3.jpg',
      id: 'FF3',
      category: 'c1',
      isMustTry: true,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Bhelpuri',
      imageUrl: 'assets/foods/4.jpg',
      id: 'FF4',
      category: 'c1',
      isMustTry: false,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Alu Kabli',
      imageUrl: 'assets/foods/5.jpg',
      id: 'FF5',
      category: 'c1',
      isMustTry: false,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Chur Mur',
      imageUrl: 'assets/foods/6.jpg',
      id: 'FF6',
      category: 'c1',
      isMustTry: false,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Alu Bhaja',
      imageUrl: 'assets/foods/7.jpg',
      id: 'B1',
      category: 'c2',
      isMustTry: false,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Begun Bhaja',
      imageUrl: 'assets/foods/8.jpg',
      id: 'B2',
      category: 'c2',
      isMustTry: false,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Potol Bhaja',
      imageUrl: 'assets/foods/9.jpg',
      id: 'B3',
      category: 'c2',
      isMustTry: false,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Rosogolla',
      imageUrl: 'assets/foods/10.jpg',
      id: 'M1',
      category: 'c3',
      isMustTry: true,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Nolen Gurer Sondesh',
      imageUrl: 'assets/foods/11.jpg',
      id: 'M2',
      category: 'c3',
      isMustTry: true,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Misti Doi',
      imageUrl: 'assets/foods/12.jpg',
      id: 'M3',
      category: 'c3',
      isMustTry: true,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Pithe',
      imageUrl: 'assets/foods/13.jpg',
      id: 'M4',
      category: 'c3',
      isMustTry: true,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Lyangcha',
      imageUrl: 'assets/foods/14.jpg',
      id: 'M5',
      category: 'c3',
      isMustTry: true,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Mowa',
      imageUrl: 'assets/foods/15.jpg',
      id: 'M6',
      category: 'c3',
      isMustTry: false,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Firni',
      imageUrl: 'assets/foods/16.jpg',
      id: 'M7',
      category: 'c3',
      isMustTry: false,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Mihidana and SitaBhog',
      imageUrl: 'assets/foods/17.jpg',
      id: 'M8',
      category: 'c3',
      isMustTry: false,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Pantua',
      imageUrl: 'assets/foods/18.jpg',
      id: 'M9',
      category: 'c3',
      isMustTry: true,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Kolkata Dum Biriyani',
      imageUrl: 'assets/foods/19.jpg',
      id: 'S1',
      category: 'c4',
      isMustTry: true,
      isNonVeg: true,
      isVeg: false,),
  Meal(
      title: 'Luchi and Cholar Dal',
      imageUrl: 'assets/foods/20.jpg',
      id: 'S2',
      category: 'c4',
      isMustTry: true,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Luchi and Alur Dum',
      imageUrl: 'assets/foods/21.jpg',
      id: 'S3',
      category: 'c4',
      isMustTry: true,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Muri Ghonto',
      imageUrl: 'assets/foods/22.jpg',
      id: 'S4',
      category: 'c4',
      isMustTry: false,
      isNonVeg: true,
      isVeg: false,),
  Meal(
      title: 'Ghugni',
      imageUrl: 'assets/foods/23.jpg',
      id: 'S5',
      category: 'c4',
      isMustTry: true,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Mung Dal',
      imageUrl: 'assets/foods/24.jpg',
      id: 'S6',
      category: 'c4',
      isMustTry: false,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Begun Pora',
      imageUrl: 'assets/foods/25.jpg',
      id: 'S7',
      category: 'c4',
      isMustTry: false,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Bhapa Sorshe Ilish',
      imageUrl: 'assets/foods/26.jpg',
      id: 'F1',
      category: 'c5',
      isMustTry: true,
      isNonVeg: true,
      isVeg: false,),
  Meal(
      title: 'Lote Macher Jhuri',
      imageUrl: 'assets/foods/27.jpg',
      id: 'F2',
      category: 'c5',
      isMustTry: false,
      isNonVeg: true,
      isVeg: false,),
  Meal(
      title: 'Bhetki Paturi',
      imageUrl: 'assets/foods/28.jpg',
      id: 'F3',
      category: 'c5',
      isMustTry: true,
      isNonVeg: true,
      isVeg: false,),
  Meal(
      title: 'Chingri Macher Malaikari',
      imageUrl: 'assets/foods/29.jpg',
      id: 'F4',
      category: 'c5',
      isMustTry: true,
      isNonVeg: true,
      isVeg: false,),
  Meal(
      title: 'Katla Kalia',
      imageUrl: 'assets/foods/30.jpg',
      id: 'F5',
      category: 'c5',
      isMustTry: true,
      isNonVeg: true,
      isVeg: false,),
  Meal(
      title: 'Shorshe Pabdar Jhal',
      imageUrl: 'assets/foods/31.jpg',
      id: 'F6',
      category: 'c5',
      isMustTry: true,
      isNonVeg: true,
      isVeg: false,),
  Meal(
      title: 'Dab Chingri',
      imageUrl: 'assets/foods/32.jpg',
      id: 'F7',
      category: 'c5',
      isMustTry: true,
      isNonVeg: true,
      isVeg: false,),
  Meal(
      title: 'Chitol Macher Muitha',
      imageUrl: 'assets/foods/33.jpg',
      id: 'F8',
      category: 'c5',
      isMustTry: false,
      isNonVeg: true,
      isVeg: false,),
  Meal(
      title: 'Kochi Pathar Jhol',
      imageUrl: 'assets/foods/34.jpg',
      id: 'ma5',
      category: 'c6',
      isMustTry: true,
      isNonVeg: true,
      isVeg: false,),
  Meal(
      title: 'Kosha Mangsho',
      imageUrl: 'assets/foods/35.jpg',
      id: 'ma6',
      category: 'c6',
      isMustTry: true,
      isNonVeg: true,
      isVeg: false,),
  Meal(
      title: 'Balti Chicken',
      imageUrl: 'assets/foods/36.jpg',
      id: 'ma7',
      category: 'c6',
      isMustTry: true,
      isNonVeg: true,
      isVeg: false,),
  Meal(
      title: 'Alu Posto',
      imageUrl: 'assets/foods/37.jpg',
      id: 't1',
      category: 'c7',
      isMustTry: true,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Shukto',
      imageUrl: 'assets/foods/38.jpg',
      id: 't2',
      category: 'c7',
      isMustTry: true,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Dhokar Dalna',
      imageUrl: 'assets/foods/39.jpg',
      id: 't3',
      category: 'c7',
      isMustTry: true,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Doi Potol',
      imageUrl: 'assets/foods/40.jpg',
      id: 't4',
      category: 'c7',
      isMustTry: true,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Chanar Dalna',
      imageUrl: 'assets/foods/41.jpg',
      id: 't5',
      category: 'c7',
      isMustTry: true,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Mocha Ghonto',
      imageUrl: 'assets/foods/42.jpg',
      id: 't6',
      category: 'c7',
      isMustTry: false,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Labra',
      imageUrl: 'assets/foods/43.jpg',
      id: 't7',
      category: 'c7',
      isMustTry: false,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Echorer Dalna',
      imageUrl: 'assets/foods/44.jpg',
      id: 't8',
      category: 'c7',
      isMustTry: false,
      isVeg: true,
      isNonVeg: false),
  Meal(
      title: 'Lau Chingri',
      imageUrl: 'assets/foods/45.jpg',
      id: 't9',
      category: 'c7',
      isMustTry: true,
      isNonVeg: true),
  Meal(
      title: 'Kachkolar Kopta',
      imageUrl: 'assets/foods/46.jpg',
      id: 't10',
      category: 'c7',
      isMustTry: false,
      isVeg: true,
      isNonVeg: false),
];
